In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/user/OneDrive/Desktop/새 폴더/data/processed/0507_userindex.csv')
mart = pd.read_csv('C:/Users/user/OneDrive/Desktop/새 폴더/data/processed/vod_mart_processed.csv')

C:\Users\user\AppData\Local\Temp\ipykernel_11812\2669181414.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  mart = pd.read_csv('C:/Users/user/OneDrive/Desktop/새 폴더/data/processed/vod_mart_processed.csv')

In [ ]:
df.drop(columns = {'sha2_hash', 'user_label', 'asset_nm'}, inplace = True)

In [17]:
# mart에서 필요한 컬럼만 선택
mart_subset = mart[['asset_id', 'super_asset_nm']]

# df와 mart_subset을 asset_id를 기준으로 병합
df = pd.merge(df, mart_subset, on='asset_id', how='left')

# 결과 확인
print(f"병합 후 데이터 크기: {df.shape}")
print(f"super_asset_nm 컬럼의 결측치 수: {df['super_asset_nm'].isnull().sum()}")

병합 후 데이터 크기: (17175103, 6)
super_asset_nm 컬럼의 결측치 수: 0

In [19]:
# mart에서 필요한 컬럼만 선택
mart_subset = mart[['asset_id', 'category_l1', 'category_l2']]

# df와 mart_subset을 asset_id를 기준으로 병합
df = pd.merge(df, mart_subset, on='asset_id', how='left')

# 결과 확인
print(f"병합 후 데이터 크기: {df.shape}")
print(f"category_l1 컬럼의 결측치 수: {df['category_l1'].isnull().sum()}")
print(f"category_l2 컬럼의 결측치 수: {df['category_l2'].isnull().sum()}")

병합 후 데이터 크기: (17175103, 8)
category_l1 컬럼의 결측치 수: 0
category_l2 컬럼의 결측치 수: 0

In [20]:
# mart에서 필요한 컬럼만 선택
mart_subset = mart[['asset_id', 'genre']]

# df와 mart_subset을 asset_id를 기준으로 병합
df = pd.merge(df, mart_subset, on='asset_id', how='left')

# 결과 확인
print(f"병합 후 데이터 크기: {df.shape}")
print(f"genre 컬럼의 결측치 수: {df['genre'].isnull().sum()}")

병합 후 데이터 크기: (17175103, 9)
genre 컬럼의 결측치 수: 0

In [24]:
df

,use_tms,disp_rtm,asset_id,strt_dt_dt,user_index,super_asset_nm,category_l2,genre
0,2880,2880,M5047991LFOJ44245901,2023-05-03 22:38:06,0,전국민민원해결프로젝트-일꾼의탄생,(HD)KBS 시사교양,시사/교양
1,926,5580,M5164421LFOI39723501,2023-05-03 17:24:13,1,나 혼자산다,(HD)MBC 연예오락,연예/오락
2,500,3660,M0191290LSGK72289001,2023-05-03 16:09:53,2,명성황후(하),KBS구작,미니시리즈
3,0,4320,M5092600LFOK59331601,2023-05-03 23:39:48,3,꼬리에꼬리를무는그날이야기,(HD)SBS 시사교양,시사/교양
4,5580,5580,M5066112LFOJ84983101,2023-05-03 18:48:46,4,골 때리는 그녀들,(HD)SBS 연예오락,연예/오락
...,...,...,...,...,...,...,...,...
17175098,12,1140,M4789223LSGJ69166601,2023-05-14 20:40:29,8419,헤이지니 럭키강이 시즌14 스페셜.,만화동산,기타
17175099,4920,4920,M5143337LFOL00172201,2023-05-14 12:17:02,8416,한문철의 블랙박스 리뷰,JTBC시사교양,교양다큐
17175100,2769,4380,M4923883LSGJ81263001,2023-05-14 18:12:17,37101,심야괴담회(정규),MBC구작,연예/오락
17175101,694,5220,M5042751LFOJ31748801,2023-05-14 13:29:21,67596,런닝맨,(HD)SBS 연예오락,연예/오락
17175102,1806,2700,M5061625LSVJ84216001,2023-05-14 11:13:28,8409,차시천하(상),무비n시리즈,외화 시리즈

In [15]:
mart

,asset_id,actr_disp,asset_nm,asset_prod,broad_ymd,category,category_l1,category_l2,category_l3,category_l4,...,super_asset_id,super_asset_nm,super_asset_sq,ttl,updated,wrtr_disp,asset_nm_free,asset_nm_video_translation,asset_nm_preview,asset_nm_name
0,CCS00000000000000101,"양택조,김영환",건강 체조,FOD,NaN,지역콘텐츠/CCS충북/건강 체조,지역콘텐츠,CCS충북,건강 체조,NaN,...,null-00001,건강 체조,3665478.0,건강 체조,2.021113e+13,NaN,1,0,0,건강 체조
1,CCS00000000000000601,-,자연을 닮은 농부들,FOD,NaN,지역콘텐츠/CCS충북/의림지뜰 사람들,지역콘텐츠,CCS충북,의림지뜰 사람들,NaN,...,null-00001,자연을 닮은 농부들,3665478.0,자연을 닮은 농부들,2.021122e+13,-,1,0,0,자연을 닮은 농부들
2,CCS00000000000000701,-,가을의 추억,FOD,NaN,지역콘텐츠/CCS충북/의림지뜰 사람들,지역콘텐츠,CCS충북,의림지뜰 사람들,NaN,...,null-00002,가을의 추억,3681993.0,가을의 추억,2.021123e+13,-,1,0,0,가을의 추억
3,CCS00000000000000801,-,덤벙김치 담그는 날,FOD,NaN,지역콘텐츠/CCS충북/의림지뜰 사람들,지역콘텐츠,CCS충북,의림지뜰 사람들,NaN,...,null-00003,덤벙김치 담그는 날,3681992.0,덤벙김치 담그는 날,2.021123e+13,-,1,0,0,덤벙김치 담그는 날
4,CCS00000000000000901,-,새로운 도전의 시작,FOD,NaN,지역콘텐츠/CCS충북/의림지뜰 사람들,지역콘텐츠,CCS충북,의림지뜰 사람들,NaN,...,null-00004,새로운 도전의 시작,3698788.0,새로운 도전의 시작,2.021123e+13,-,1,0,0,새로운 도전의 시작
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412364,M4805133LSVD97884201,"왕뤄단,임봉,주려기,션타이",위황후전 37회.,SVOD,20200313,해외드라마/무비n시리즈/위황후전,해외드라마,무비n시리즈,위황후전,NaN,...,T20150813005506-00037,위황후전,412403.0,위황후전 37회.,2.020031e+13,유가호,1,0,0,위황후전
412365,M4805133LSVL28568601,"왕뤄단,임봉,주려기,션타이",위황후전 37회.,SVOD,20200313,해외드라마/무비n시리즈/위황후전,해외드라마,무비n시리즈,위황후전,NaN,...,T20150813005506-00037,위황후전,412403.0,위황후전 37회.,2.023012e+13,유가호,1,0,0,위황후전
412366,M4805134LSVD97868301,"왕뤄단,임봉,주려기,션타이",위황후전 23회.,SVOD,20200313,해외드라마/무비n시리즈/위황후전,해외드라마,무비n시리즈,위황후전,NaN,...,T20150813005506-00023,위황후전,391841.0,위황후전 23회.,2.020031e+13,유가호,1,0,0,위황후전
412367,M4805134LSVL28567201,"왕뤄단,임봉,주려기,션타이",위황후전 23회.,SVOD,20200313,해외드라마/무비n시리즈/위황후전,해외드라마,무비n시리즈,위황후전,NaN,...,T20150813005506-00023,위황후전,391841.0,위황후전 23회.,2.023012e+13,유가호,1,0,0,위황후전
412368,M4805135LSVL28569501,"왕뤄단,임봉,주려기,션타이",위황후전 46회.,SVOD,20200313,해외드라마/무비n시리즈/위황후전,해외드라마,무비n시리즈,위황후전,NaN,...,T20150813005506-00046,위황후전,336106.0,위황후전 46회.,2.023012e+13,유가호,1,0,0,위황후전